### ISSUE TITLE
Date code bug

### ISSUE THREAD

**Issue by knaughten** [knaughten/nemo_python#2]
https://github.com/knaughten/nemo_python/blob/5ff0c969c573ea8d2292d906a5f2bfcf056f8321/timeseries.py#L304

Hi Birgit, looks like you implemented this change while I was away to make extracting the file date codes (eg 18500101-18500201) more sophisticated and configuation-agnostic. Unfortunately this new formulation is not working for UKESM as the date code is spliced with "-" instead of "_". I put in a temporary fix but there is probably a way to do it more nicely. 

In UKESM the files look like, for example, 'nemo_cx209o_1m_18500101-18500201_grid-T.nc', so the output of your date code formulation was '18500101-18500201_grid-T.nc'. I'm not sure off the top of my head how the file names look in standalone NEMO 4.2.

**Comment by brogalla** [comment]
Whoops accidentally closed the issue. I've implemented a more general fix now [@commit f66f261](https://github.com/knaughten/nemo_python/commit/f66f2611c843014b707bacd851110016f6f1f09a)

**Comment by knaughten** [comment]
Thanks, seems to be fixed for me!
