### ISSUE TITLE
file_pattern needs to include both starting and ending date

### ISSUE THREAD

**Issue by knaughten** [knaughten/nemo_python#3]
https://github.com/knaughten/nemo_python/blob/e5a6ab72ba8dab3ffa36aeba552ce88880d52018/timeseries.py#L323

The new construction of file_pattern only includes the starting date, eg 'nemo_de963o_1m_22990501*-T.nc'

In order for the following checks (isf-T without grid-T or vice versa) to make sense, it needs to include the ending date too, eg 'nemo_de963o_1m_22990501-22990601*-T.nc'

I'll add a simple fix but this will follow UKESM file conventions; have a check and make sure it doesn't break your code.

**Comment by brogalla** [comment]
Thanks for the heads up! This option doesn't quite work for my code because my filenames have an underscore instead of a dash. But, replacing the dash with a wildcard fixes that (85915ac6bce477d869e4fc1234bf3f172e15af2c).
